/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Reputation } from "./Reputation";
import { ReputationCountArgs } from "./ReputationCountArgs";
import { ReputationFindManyArgs } from "./ReputationFindManyArgs";
import { ReputationFindUniqueArgs } from "./ReputationFindUniqueArgs";
import { CreateReputationArgs } from "./CreateReputationArgs";
import { UpdateReputationArgs } from "./UpdateReputationArgs";
import { DeleteReputationArgs } from "./DeleteReputationArgs";
import { User } from "../../user/base/User";
import { ReputationService } from "../reputation.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Reputation)
export class ReputationResolverBase {
  constructor(
    protected readonly service: ReputationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Reputation",
    action: "read",
    possession: "any",
  })
  async _reputationsMeta(
    @graphql.Args() args: ReputationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Reputation])
  @nestAccessControl.UseRoles({
    resource: "Reputation",
    action: "read",
    possession: "any",
  })
  async reputations(
    @graphql.Args() args: ReputationFindManyArgs
  ): Promise<Reputation[]> {
    return this.service.reputations(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Reputation, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Reputation",
    action: "read",
    possession: "own",
  })
  async reputation(
    @graphql.Args() args: ReputationFindUniqueArgs
  ): Promise<Reputation | null> {
    const result = await this.service.reputation(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Reputation)
  @nestAccessControl.UseRoles({
    resource: "Reputation",
    action: "create",
    possession: "any",
  })
  async createReputation(
    @graphql.Args() args: CreateReputationArgs
  ): Promise<Reputation> {
    return await this.service.createReputation({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Reputation)
  @nestAccessControl.UseRoles({
    resource: "Reputation",
    action: "update",
    possession: "any",
  })
  async updateReputation(
    @graphql.Args() args: UpdateReputationArgs
  ): Promise<Reputation | null> {
    try {
      return await this.service.updateReputation({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Reputation)
  @nestAccessControl.UseRoles({
    resource: "Reputation",
    action: "delete",
    possession: "any",
  })
  async deleteReputation(
    @graphql.Args() args: DeleteReputationArgs
  ): Promise<Reputation | null> {
    try {
      return await this.service.deleteReputation(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: Reputation): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
