/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Reward } from "./Reward";
import { RewardCountArgs } from "./RewardCountArgs";
import { RewardFindManyArgs } from "./RewardFindManyArgs";
import { RewardFindUniqueArgs } from "./RewardFindUniqueArgs";
import { CreateRewardArgs } from "./CreateRewardArgs";
import { UpdateRewardArgs } from "./UpdateRewardArgs";
import { DeleteRewardArgs } from "./DeleteRewardArgs";
import { QuestFindManyArgs } from "../../quest/base/QuestFindManyArgs";
import { Quest } from "../../quest/base/Quest";
import { RewardService } from "../reward.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Reward)
export class RewardResolverBase {
  constructor(
    protected readonly service: RewardService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Reward",
    action: "read",
    possession: "any",
  })
  async _rewardsMeta(
    @graphql.Args() args: RewardCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Reward])
  @nestAccessControl.UseRoles({
    resource: "Reward",
    action: "read",
    possession: "any",
  })
  async rewards(@graphql.Args() args: RewardFindManyArgs): Promise<Reward[]> {
    return this.service.rewards(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Reward, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Reward",
    action: "read",
    possession: "own",
  })
  async reward(
    @graphql.Args() args: RewardFindUniqueArgs
  ): Promise<Reward | null> {
    const result = await this.service.reward(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Reward)
  @nestAccessControl.UseRoles({
    resource: "Reward",
    action: "create",
    possession: "any",
  })
  async createReward(@graphql.Args() args: CreateRewardArgs): Promise<Reward> {
    return await this.service.createReward({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Reward)
  @nestAccessControl.UseRoles({
    resource: "Reward",
    action: "update",
    possession: "any",
  })
  async updateReward(
    @graphql.Args() args: UpdateRewardArgs
  ): Promise<Reward | null> {
    try {
      return await this.service.updateReward({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Reward)
  @nestAccessControl.UseRoles({
    resource: "Reward",
    action: "delete",
    possession: "any",
  })
  async deleteReward(
    @graphql.Args() args: DeleteRewardArgs
  ): Promise<Reward | null> {
    try {
      return await this.service.deleteReward(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Quest], { name: "quests" })
  @nestAccessControl.UseRoles({
    resource: "Quest",
    action: "read",
    possession: "any",
  })
  async findQuests(
    @graphql.Parent() parent: Reward,
    @graphql.Args() args: QuestFindManyArgs
  ): Promise<Quest[]> {
    const results = await this.service.findQuests(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
