include:
  - ../apps/social-mmo-server/docker-compose.yml
version: "3"
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:debian
    command: sleep infinity
    links:
      - server
