/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { QuestService } from "../quest.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { QuestCreateInput } from "./QuestCreateInput";
import { Quest } from "./Quest";
import { Post } from "../../post/base/Post";
import { QuestFindManyArgs } from "./QuestFindManyArgs";
import { QuestWhereUniqueInput } from "./QuestWhereUniqueInput";
import { QuestUpdateInput } from "./QuestUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class QuestControllerBase {
  constructor(
    protected readonly service: QuestService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Quest })
  @nestAccessControl.UseRoles({
    resource: "Quest",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: QuestCreateInput,
  })
  async createQuest(@common.Body() data: QuestCreateInput): Promise<Quest> {
    return await this.service.createQuest({
      data: {
        ...data,

        reward: data.reward
          ? {
              connect: data.reward,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        description: true,
        reputationRequired: true,

        reward: {
          select: {
            id: true,
          },
        },

        name: true,
        questName: true,
        questDescription: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Quest] })
  @ApiNestedQuery(QuestFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Quest",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async quests(@common.Req() request: Request): Promise<Quest[]> {
    const args = plainToClass(QuestFindManyArgs, request.query);
    return this.service.quests({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        description: true,
        reputationRequired: true,

        reward: {
          select: {
            id: true,
          },
        },

        name: true,
        questName: true,
        questDescription: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Quest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Quest",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async quest(
    @common.Param() params: QuestWhereUniqueInput
  ): Promise<Quest | null> {
    const result = await this.service.quest({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        description: true,
        reputationRequired: true,

        reward: {
          select: {
            id: true,
          },
        },

        name: true,
        questName: true,
        questDescription: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Quest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Quest",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: QuestUpdateInput,
  })
  async updateQuest(
    @common.Param() params: QuestWhereUniqueInput,
    @common.Body() data: QuestUpdateInput
  ): Promise<Quest | null> {
    try {
      return await this.service.updateQuest({
        where: params,
        data: {
          ...data,

          reward: data.reward
            ? {
                connect: data.reward,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          title: true,
          description: true,
          reputationRequired: true,

          reward: {
            select: {
              id: true,
            },
          },

          name: true,
          questName: true,
          questDescription: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Quest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Quest",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteQuest(
    @common.Param() params: QuestWhereUniqueInput
  ): Promise<Quest | null> {
    try {
      return await this.service.deleteQuest({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          title: true,
          description: true,
          reputationRequired: true,

          reward: {
            select: {
              id: true,
            },
          },

          name: true,
          questName: true,
          questDescription: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
