/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Quest } from "./Quest";
import { QuestCountArgs } from "./QuestCountArgs";
import { QuestFindManyArgs } from "./QuestFindManyArgs";
import { QuestFindUniqueArgs } from "./QuestFindUniqueArgs";
import { CreateQuestArgs } from "./CreateQuestArgs";
import { UpdateQuestArgs } from "./UpdateQuestArgs";
import { DeleteQuestArgs } from "./DeleteQuestArgs";
import { Reward } from "../../reward/base/Reward";
import { QuestService } from "../quest.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Quest)
export class QuestResolverBase {
  constructor(
    protected readonly service: QuestService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Quest",
    action: "read",
    possession: "any",
  })
  async _questsMeta(
    @graphql.Args() args: QuestCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Quest])
  @nestAccessControl.UseRoles({
    resource: "Quest",
    action: "read",
    possession: "any",
  })
  async quests(@graphql.Args() args: QuestFindManyArgs): Promise<Quest[]> {
    return this.service.quests(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Quest, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Quest",
    action: "read",
    possession: "own",
  })
  async quest(
    @graphql.Args() args: QuestFindUniqueArgs
  ): Promise<Quest | null> {
    const result = await this.service.quest(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Quest)
  @nestAccessControl.UseRoles({
    resource: "Quest",
    action: "create",
    possession: "any",
  })
  async createQuest(@graphql.Args() args: CreateQuestArgs): Promise<Quest> {
    return await this.service.createQuest({
      ...args,
      data: {
        ...args.data,

        reward: args.data.reward
          ? {
              connect: args.data.reward,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Quest)
  @nestAccessControl.UseRoles({
    resource: "Quest",
    action: "update",
    possession: "any",
  })
  async updateQuest(
    @graphql.Args() args: UpdateQuestArgs
  ): Promise<Quest | null> {
    try {
      return await this.service.updateQuest({
        ...args,
        data: {
          ...args.data,

          reward: args.data.reward
            ? {
                connect: args.data.reward,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Quest)
  @nestAccessControl.UseRoles({
    resource: "Quest",
    action: "delete",
    possession: "any",
  })
  async deleteQuest(
    @graphql.Args() args: DeleteQuestArgs
  ): Promise<Quest | null> {
    try {
      return await this.service.deleteQuest(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Reward, {
    nullable: true,
    name: "reward",
  })
  @nestAccessControl.UseRoles({
    resource: "Reward",
    action: "read",
    possession: "any",
  })
  async getReward(@graphql.Parent() parent: Quest): Promise<Reward | null> {
    const result = await this.service.getReward(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
